Repository pkgxdev/pkgx, pull requests merged in 2024-09, with the labels that each got.

#1030 sync log messages
  deno.lock
  src/app.ts
  src/modes/x.ts
  src/prefab/failsafe.ts
Labels: size:M

#978 Use deno 1.45: binaries ~25% smaller, ~10% faster
  .github/workflows/ci.shellcode.yml
  .github/workflows/ci.yml
  deno.jsonc
  deno.lock
  entrypoint.ts
  src/app.ts
  src/modes/integrate.ts
  src/utils/clicolor.ts
  src/utils/execve.test.ts
  src/utils/execve.ts
Labels: size:M, lgtm

#986 Fix typo: remove redundant backticks
  docs/faq.md
Labels: size:XS

#1000 Escape spaces in stubs for uninstallation
  src/modes/install.ts
Labels: size:XS, lgtm

#1011 feat(dev): added support for justfiles
  src/utils/devenv.ts
Labels: size:XS, lgtm

#979 Fix dev off when environment is not active
  src/modes/internal.activate.ts
  src/modes/shellcode.ts
Labels: size:S

#980 Discover pkgs from volta and corepack
  fixtures/package.json/engines/package.json
  fixtures/package.json/packageManager/package.json
  fixtures/package.json/volta/package.json
  src/utils/devenv.test.ts
  src/utils/devenv.ts
Labels: size:M, lgtm

#1008 feat(install): add support for `--unsafe` install flag
  src/app.ts
  src/modes/install.ts
  src/modes/uninstall.ts
  src/parse-args.ts
Labels: size:M

#1032 Update terminals
  docs/run/anywhere/terminals.md
Labels: size:XS

#999 Error when a different version is already installed
  src/modes/install.ts
Labels: size:XS

#1031 v1.2-rc
  .github/workflows/ci.shellcode.yml
  .github/workflows/ci.yml
  deno.jsonc
  deno.lock
Labels: size:S
